import { CSSProperties, FC, ReactNode } from "react";
import "./index.css";
export declare type ButtonProps = {
    label?: ReactNode | string;
    Link?: any;
    icon?: ReactNode;
    className?: string;
    loading?: boolean;
    onClick?: () => any;
    disabled?: boolean;
    style?: CSSProperties;
    href?: string;
    to?: string;
    spinnerBgColor?: string;
    spinnerColor?: string;
    spinnerSize?: number;
    type?: "button" | "submit" | "reset" | undefined;
    ripple?: boolean;
};
declare const Button: FC<ButtonProps>;
export default Button;
